# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for more information:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
# https://containers.dev/guide/dependabot

version: 2
updates:
  - package-ecosystem: "devcontainers"
    directory: "/"
    schedule:
      interval: weekly
    cooldown:
      default-days: 5
    groups:
      all-dependencies:
        patterns:
          - "*"
    open-pull-requests-limit: 5
    assignees:
      - "manaten"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: weekly
    groups:
      prod-major-updates:
        # dependabot不具合のため、一時的にコメントアウト
        # ref https://github.com/dependabot/dependabot-core/issues/13154
        #
        # patterns:
        #   - "*"
        dependency-type: "production"
        update-types:
          - "major"
      dev-major-updates:
        # patterns:
        #   - "*"
        dependency-type: "development"
        update-types:
          - "major"
      prod-minor-patch-updates:
        # patterns:
        #   - "*"
        dependency-type: "production"
        update-types:
          - "minor"
          - "patch"
      dev-minor-patch-updates:
        # patterns:
        #   - "*"
        dependency-type: "development"
        update-types:
          - "minor"
          - "patch"

    open-pull-requests-limit: 5
    assignees:
      - "manaten"
